[package]
name = "gba-tools"
version = "0.1.0"
authors = ["Tibor Nagy <xnagytibor@gmail.com>"]

[dependencies]
byteorder = "1.1.0"
docopt = "0.8.1"
gba-compression = { git = "https://github.com/xtibor/gba-compression" }
serde = "1.0"
serde_derive = "1.0"
